/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.lab;

import javax.swing.JOptionPane;

/**
 *
 * @author Toshiba
 */
public class LabReport extends javax.swing.JFrame {

    String testNumber;
    public LabReport() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleName = new javax.swing.JLabel();
        reportName = new javax.swing.JLabel();
        patientID = new javax.swing.JLabel();
        testID = new javax.swing.JLabel();
        testName = new javax.swing.JLabel();
        textPatientID = new javax.swing.JTextField();
        textTestNo = new javax.swing.JTextField();
        textTestName = new javax.swing.JTextField();
        detailsOfTestLable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsOfTest = new javax.swing.JTextArea();
        labTechnicianID = new javax.swing.JLabel();
        textLabTechnicianID = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("COOPERATIVE HOSPITAL - MATARA");

        reportName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        reportName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportName.setText("Patient Lab Report");

        patientID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        patientID.setText("Patient ID:");

        testID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        testID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        testID.setText("Test ID :");

        testName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        testName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        testName.setText("Test Name:");

        textPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientIDActionPerformed(evt);
            }
        });

        textTestNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestNoActionPerformed(evt);
            }
        });
        textTestNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTestNoKeyPressed(evt);
            }
        });

        textTestName.setEditable(false);
        textTestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTestNameActionPerformed(evt);
            }
        });

        detailsOfTestLable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        detailsOfTestLable.setText("Details of the test");

        detailsOfTest.setColumns(20);
        detailsOfTest.setRows(5);
        jScrollPane1.setViewportView(detailsOfTest);

        labTechnicianID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labTechnicianID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labTechnicianID.setText("Lab Technician ID:");

        textLabTechnicianID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        date.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("Date:");

        textDate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(103, 103, 103)
                        .addComponent(testID, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTestNo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(100, 100, 100)
                        .addComponent(testName, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTestName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(detailsOfTestLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labTechnicianID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textLabTechnicianID)
                        .addGap(422, 422, 422)
                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientID)
                        .addComponent(textPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textTestNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(testName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(testID)))
                .addGap(18, 18, 18)
                .addComponent(detailsOfTestLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTechnicianID)
                    .addComponent(textLabTechnicianID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientIDActionPerformed

    private void textTestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestNameActionPerformed
        
        
    }//GEN-LAST:event_textTestNameActionPerformed

    private void textTestNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTestNoActionPerformed
        
    }//GEN-LAST:event_textTestNoActionPerformed

    private void textTestNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTestNoKeyPressed
        
        if(evt.getKeyCode()==10){
            switch (textTestNo.getText()) {
                case "01":
                    textTestName.setText("Fasting Blood Suger");
                    break;
                case "02":
                    textTestName.setText("Urine Filtration Rate");
                    break;
                default:
                    textTestNo.setText(null);
                    JOptionPane.showMessageDialog(textTestNo,"Test number is incorrect..!");
                    break;
            }
        }
    }//GEN-LAST:event_textTestNoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LabReport l=new LabReport();
                l.setTitle("Lab Report");
                l.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTextArea detailsOfTest;
    private javax.swing.JLabel detailsOfTestLable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTechnicianID;
    private javax.swing.JLabel patientID;
    private javax.swing.JLabel reportName;
    private javax.swing.JLabel testID;
    private javax.swing.JLabel testName;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textLabTechnicianID;
    private javax.swing.JTextField textPatientID;
    private javax.swing.JTextField textTestName;
    private javax.swing.JTextField textTestNo;
    private javax.swing.JLabel titleName;
    // End of variables declaration//GEN-END:variables
}
